### ISSUE TITLE
Update styling

### ISSUE THREAD

**Issue by crooksey** [Pylons/pylonshq#56]
Whats everyones thoughts of an overhaul and new theme? The debug toolbar now uses the new colours shown at http://trypyramid.com/ .

Are there any plans to update the site, If I was to start this would any be in favour of it/willing to help?

**Comment by blaflamme** [comment]
Look here if you want to participate in the discussion

https://groups.google.com/forum/#!topic/pylons-discuss/vhQuxp-TNX4

**Comment by mikeorr** [comment]
I like the yellow and black gradient on the current site; it seems more
like an Egyptian desert. Another gradient might be OK but red might connote
too much fire engines and stop signs.

On Wed, Oct 1, 2014 at 11:53 AM, Luke Crooks <notifications@github.com>
wrote:

> Whats everyones thoughts of an overhaul and new theme? The debug toolbar
> now uses the new colours shown at http://trypyramid.com/ .
>
> Are there any plans to update the site, If I was to start this would any
> be in favour of it/willing to help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pylons/pylonshq/issues/56>.
>



-- 
Mike Orr <sluggoster@gmail.com>

**Comment by blaflamme** [comment]
The new site will not share any egyptian relation. It will be reworked and based on new color schemes from both new pylons and pyramid logos. The new scaffold could gives you the tone; flat colors, tints and contrasts.

For egyptian style you should look at our annually tee design :)
